Repository jellyfin/jellyfin-plugin-trakt, pull requests merged in 2022-10, with the labels that each got.

#171 Add more info to debug logs
  Trakt/ScheduledTasks/SyncFromTraktTask.cs
Labels: chore

#169 Prevent setting local item as unwatched on sync
  Trakt/ScheduledTasks/SyncLibraryTask.cs
Labels: bug

#175 Do not hammer the API
  Trakt/Api/DataContracts/Users/Playback/TraktEpisodePaused.cs
  Trakt/Api/DataContracts/Users/Playback/TraktMoviePaused.cs
  Trakt/Api/TraktURIs.cs
  Trakt/Model/PlaybackState.cs
  Trakt/ServerMediator.cs
Labels: bug, feature
