Repository jellyfin/jellyfin-plugin-trakt, pull requests merged in 2022-04, with the labels that each got.

#114 Implement deauth
  Trakt/Api/TraktApi.cs
  Trakt/Api/TraktController.cs
  Trakt/Api/TraktURIs.cs
  Trakt/Configuration/PluginConfiguration.cs
  Trakt/Web/trakt.html
  Trakt/Web/trakt.js
Labels: feature

#111 Add pagination to scheduled tasks
  Trakt/ScheduledTasks/SyncFromTraktTask.cs
  Trakt/ScheduledTasks/SyncLibraryTask.cs
  Trakt/Trakt.csproj
Labels: feature

#115 Require success response before deserializing
  Trakt/Api/TraktApi.cs
Labels: bug

#117 Send pause instead of stop on uncompleted playback to prevent scrobble
  Trakt/ServerMediator.cs
Labels: bug

#119 Update .Net version in readme
  README.md
Labels: chore

#120 Implement handling of update events and progress sync, fix scheduled tasks
  Trakt/Api/DataContracts/BaseModel/TraktEpisode.cs
  Trakt/Api/DataContracts/BaseModel/TraktIMDBandTMDBId.cs
  Trakt/Api/DataContracts/BaseModel/TraktTVId.cs
  Trakt/Api/DataContracts/Sync/Items.cs
  Trakt/Api/DataContracts/Sync/TraktSyncResponse.cs
  Trakt/Api/DataContracts/Users/Collection/TraktMovieCollected.cs
  Trakt/Api/DataContracts/Users/Collection/TraktShowCollected.cs
  Trakt/Api/DataContracts/Users/Playback/TraktEpisodePaused.cs
  Trakt/Api/DataContracts/Users/Playback/TraktMoviePaused.cs
  Trakt/Api/DataContracts/Users/Watched/TraktEpisodeWatched.cs
  Trakt/Api/DataContracts/Users/Watched/TraktMovieWatched.cs
  Trakt/Api/DataContracts/Users/Watched/TraktShowWatched.cs
  Trakt/Api/Enums/TraktAction.cs
  Trakt/Api/TraktApi.cs
  Trakt/Api/TraktController.cs
  Trakt/Api/TraktURIs.cs
  Trakt/Extensions.cs
  Trakt/Helpers/ISplittableProgress.cs
  Trakt/Helpers/LibraryManagerEventsHelper.cs
  Trakt/Helpers/SplittableProgress.cs
  Trakt/Helpers/UserDataManagerEventsHelper.cs
  Trakt/Model/TraktUser.cs
  Trakt/Model/UserDataPackage.cs
  Trakt/ScheduledTasks/SyncFromTraktTask.cs
  Trakt/ScheduledTasks/SyncLibraryTask.cs
  Trakt/ServerMediator.cs
  Trakt/Web/trakt.html
  Trakt/Web/trakt.js
Labels: bug, feature

#123 Fix codeql warnings
  Trakt/Api/TraktApi.cs
  Trakt/Helpers/LibraryManagerEventsHelper.cs
  Trakt/Helpers/UserDataManagerEventsHelper.cs
  Trakt/ScheduledTasks/SyncFromTraktTask.cs
  Trakt/ScheduledTasks/SyncLibraryTask.cs
  Trakt/ServerMediator.cs
Labels: chore

#124 Switch to native episode number check and datetime string conversion
  Trakt/Extensions.cs
  Trakt/ScheduledTasks/SyncFromTraktTask.cs
  Trakt/ScheduledTasks/SyncLibraryTask.cs
Labels: chore

#128 Handle playback skipping and fix progress sync
  Trakt/Api/TraktApi.cs
  Trakt/Api/TraktURIs.cs
  Trakt/Model/LibraryEvent.cs
  Trakt/Model/PlaybackState.cs
  Trakt/ScheduledTasks/SyncFromTraktTask.cs
  Trakt/ScheduledTasks/SyncLibraryTask.cs
  Trakt/ServerMediator.cs
Labels: bug, feature

#127 Add retry time to BadGateway response
  Trakt/Api/TraktApi.cs
Labels: bug
