Repository jellyfin/jellyfin-plugin-trakt, pull requests merged in 2023-02, with the labels that each got.

#199 Fix episode last played date syncing
  Trakt/ScheduledTasks/SyncFromTraktTask.cs
Labels: bug

#201 Sync `LastPlayedDate` if not set locally
  Trakt/ScheduledTasks/SyncFromTraktTask.cs
Labels: bug

#196 Added config parameter Don't remove items from trakt
  Trakt/Helpers/LibraryManagerEventsHelper.cs
  Trakt/Model/TraktUser.cs
  Trakt/Web/trakt.html
  Trakt/Web/trakt.js
Labels: feature

#202 small correction to trakt.html
  Trakt/Web/trakt.html
Labels: documentation
